# Generated by Django 3.0.4 on 2020-03-30 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200330_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descrtiption',
            new_name='description',
        ),
    ]
